apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: version-demo-writeback
  namespace: argocd
spec:
  # Select which Applications this ImageUpdater manages
  applicationRefs:
    - namePattern: "version-demo"

  # Global update settings
  commonUpdateSettings:
    updateStrategy: "semver"
    forceUpdate: false

  # Configuration for specific images
  images:
    - alias: "version-demo"
      imageName: "docker.io/devlopesbernardo/version-demo"
      # Map the image tag to the helm value 'image.tag'
      manifestTargets:
        helm:
          name: "image.repository"
          tag: "image.tag"

  # Write back changes to Git
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "git@github.com:bernardolsp/img-updater.git"
      branch: "main"
      writeBackTarget: "helm/values.yaml"
      commitMessage: "chore(deps): update version-demo to {{ .NewTag }}"
      user: "ArgoCD Image Updater"
      email: "argocd-image-updater@example.com"
