apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: version-demo-no-writeback
  namespace: argocd
spec:
  namespace: argocd
  # Select which Applications this ImageUpdater manages
  applicationRefs:
    - namePattern: "version-demo"
      # Configuration for specific images
      images:
        - alias: "version-demo"
          imageName: "docker.io/devlopesbernardo/version-demo"
          # Map the image tag to the helm value 'image.tag'
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"

  # Global update settings
  commonUpdateSettings:
    updateStrategy: "semver"
    forceUpdate: true

  # Update the ArgoCD Application resource directly (stateless)
  # This does NOT write to Git
  writeBackConfig:
    method: "argocd"
